DELETE http://localhost:3001/api/blogs/6002e99afa930f56cd4ebe77
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI1ZjBkOGY4OTdkZDM3NjZmNTg4Y2ZkNTMiLCJpYXQiOjE1OTQ3MjQzMDd9.gB8PXQHol6-eZm287MpXSo1BpdEN4BVpfHoX92gsKn4